#!/usr/bin/env python3
"""
Regenerates src/main/resources/db/data/nigerian-states.sql from the pinned
geoBoundaries release of GRID3's Nigeria state boundaries (CC BY 4.0).

    curl -L -o nga-adm1.geojson \\
      https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/NGA/ADM1/geoBoundaries-NGA-ADM1.geojson
    python3 scripts/generate-nigerian-states-sql.py nga-adm1.geojson > src/main/resources/db/data/nigerian-states.sql

Changing the output changes the Liquibase checksum of changeset 064: a new
dataset version is a NEW changeset, never an edit to 064 (see AGENTS.md).
"""
import json
import sys

# Canonical names are the frontend's (~/landvault/src/data/nigerianStates.ts);
# the dataset differs only on the FCT.
CANONICAL = {"Abuja Federal Capital Territory": "Federal Capital Territory (Abuja)"}
# Spellings people actually type, matched case-insensitively. A trailing
# " state" is stripped in code, so "Lagos State" needs no entry.
ALIASES = {
    "NG-FC": ["FCT", "Abuja", "Federal Capital Territory", "Abuja Federal Capital Territory", "FCT Abuja",
              "FCT - Abuja", "Abuja FCT"],
    "NG-NA": ["Nassarawa"],
    "NG-AK": ["Akwa-Ibom"],
    "NG-CR": ["Cross-River"],
}

data = json.load(open(sys.argv[1]))
assert data["crs"]["properties"]["name"].endswith("CRS84"), "expected longitude/latitude (CRS84)"
features = sorted(data["features"], key=lambda f: f["properties"]["shapeISO"])
assert len(features) == 37, len(features)

print("-- GENERATED by scripts/generate-nigerian-states-sql.py — do not edit by hand.")
print("-- Source: GRID3 Nigeria operational state boundaries, via geoBoundaries gbOpen NGA ADM1")
print("-- (commit 9469f09; boundaries represent 2022). Licence: CC BY 4.0 — attribution required.")
for f in features:
    p = f["properties"]
    assert f["geometry"]["type"] == "Polygon", p
    code = p["shapeISO"]
    name = CANONICAL.get(p["shapeName"], p["shapeName"])
    aliases = "ARRAY[" + ",".join("'" + a.lower().replace("'", "''") + "'" for a in ALIASES.get(code, [])) + "]::text[]"
    geometry = json.dumps(f["geometry"], separators=(",", ":"))
    print(f"INSERT INTO nigerian_states (code, name, aliases, boundary) VALUES ('{code}', '{name}', {aliases}, "
          f"ST_SetSRID(ST_GeomFromGeoJSON('{geometry}'), 4326));")
